use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct TerrainConfig {
    pub width: i32,
    pub height: i32,
    pub seed: i32,
    pub octaves: i32,
    pub persistence: f64,
    pub lacunarity: f64,
    pub sea_level: f64,
    pub river_source_quantile: f64,
}

impl Default for TerrainConfig {
    fn default() -> Self {
        Self {
            width: 64,
            height: 64,
            seed: 7,
            octaves: 4,
            persistence: 0.5f64,
            lacunarity: 2.0f64,
            sea_level: 0.08f64,
            river_source_quantile: 0.8f64,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct SimulationConfig {
    pub terrain: TerrainConfig,
    pub horizon: i32,
    pub num_sites: i32,
    pub min_site_spacing: f64,
    pub seed: i32,
    pub initial_extraction_alpha: f64,
    pub initial_extraction_beta: f64,
    pub initial_extraction_resource_bias: f64,
    pub initial_openness_alpha: f64,
    pub initial_openness_beta: f64,
    pub initial_adaptability_alpha: f64,
    pub initial_adaptability_beta: f64,
    pub agglomeration_alpha: f64,
    pub extraction_drag: f64,
    pub congestion: f64,
    pub network_scale: f64,
    pub network_population_gain: f64,
    pub network_capital_gain: f64,
    pub network_density_gain: f64,
    pub resource_base_payoff: f64,
    pub resource_capture_gain: f64,
    pub extractive_cashflow_premium: f64,
    pub resource_curse_strength: f64,
    pub curse_openness_buffer: f64,
    pub curse_capital_buffer: f64,
    pub inclusive_investment_gain: f64,
    pub inclusive_productivity_gain: f64,
    pub extractive_capital_erosion: f64,
    pub secondary_city_bonus: f64,
    pub secondary_city_target: f64,
    pub secondary_city_spread: f64,
    pub metropolitan_overstretch_threshold: f64,
    pub metropolitan_overstretch_penalty: f64,
    pub endogenous_growth_rate: f64,
    pub endogenous_growth_decay: f64,
    pub endogenous_decline_rate: f64,
    pub active_extraction_pressure: f64,
    pub active_resource_depletion: f64,
    pub active_openness_drag: f64,
    pub active_decay_onset: i32,
    pub trade_cluster_count: i32,
    pub trade_cluster_radius: f64,
    pub trade_cluster_openness_bonus: f64,
    pub trade_cluster_capital_bonus: f64,
    pub trade_cluster_accessibility_bonus: f64,
    pub boomtown_count: i32,
    pub boomtown_resource_bonus: f64,
    pub boomtown_geography_penalty: f64,
    pub boomtown_initial_extraction_boost: f64,
    pub boomtown_early_reward_bonus: f64,
    pub boomtown_bonus_duration: i32,
    pub boomtown_collapse_penalty: f64,
    pub boomtown_collapse_threshold: i32,
    pub boomtown_decay_multiplier: f64,
    pub thompson_posterior_decay: f64,
    pub discounted_ucb_gamma: f64,
    pub sliding_window_ucb_window: i32,
    pub discounted_thompson_posterior_decay: f64,
    pub linucb_alpha: f64,
    pub linear_bandit_ridge: f64,
    pub linear_thompson_observation_variance: f64,
    pub linear_thompson_sampling_scale: f64,
    pub reform_sensitivity: f64,
    pub reform_step: f64,
    pub reform_duration: i32,
    pub reform_cost: f64,
    pub shock_reform_memory: i32,
    pub shock_reform_bonus: f64,
    pub shock_reform_step_bonus: f64,
    pub shock_openness_bonus: f64,
    pub shock_capital_rebuild: f64,
    pub shock_transition_duration: i32,
    pub shock_transition_adaptability_bonus: f64,
    pub shock_transition_curse_buffer: f64,
    pub shock_transition_extraction_decay: f64,
    pub shock_transition_extraction_cap: f64,
    pub shock_transition_openness_gain: f64,
    pub shock_transition_capital_gain: f64,
    pub shock_legacy_fade: f64,
    pub shock_legacy_adaptability_bonus: f64,
    pub shock_legacy_curse_buffer: f64,
    pub shock_legacy_extraction_decay: f64,
    pub shock_legacy_extraction_brake: f64,
    pub shock_legacy_openness_gain: f64,
    pub shock_readiness_weight: f64,
    pub shock_lock_in_bonus: f64,
    pub shock_snapback_pressure: f64,
    pub shock_probability: f64,
    pub depletion_rate: f64,
    pub shock_target_resource_bias: f64,
    pub geography_weights: (f64, f64, f64, f64, f64),
    pub spine_height: f64,
    pub spine_curvature: f64,
    pub taper_offset: f64,
    pub taper_curvature_x: f64,
    pub taper_bias_x: f64,
    pub taper_linear_x: f64,
    pub headland_height: f64,
    pub headland_x: f64,
    pub mainland_bridge_height: f64,
    pub shock_readiness_base: f64,
    pub shock_legacy_readiness_base: f64,
    pub reform_openness_gain: f64,
    pub reform_adaptability_gain: f64,
    pub passive_investment_scale: f64,
    pub network_openness_influence: f64,
    pub growth_structural_weight: f64,
    pub migration_threshold: f64,
    pub lod: String,
    pub run_id: i32,
}

impl Default for SimulationConfig {
    fn default() -> Self {
        Self {
            terrain: Default::default(),
            horizon: 300,
            num_sites: 15,
            min_site_spacing: 0.12f64,
            seed: 7,
            initial_extraction_alpha: 2.0f64,
            initial_extraction_beta: 5.0f64,
            initial_extraction_resource_bias: 2.5f64,
            initial_openness_alpha: 2.2f64,
            initial_openness_beta: 2.2f64,
            initial_adaptability_alpha: 3.0f64,
            initial_adaptability_beta: 3.0f64,
            agglomeration_alpha: 0.52f64,
            extraction_drag: 0.08f64,
            congestion: 0.003f64,
            network_scale: 0.35f64,
            network_population_gain: 0.12f64,
            network_capital_gain: 0.45f64,
            network_density_gain: 0.7f64,
            resource_base_payoff: 0.2f64,
            resource_capture_gain: 1.35f64,
            extractive_cashflow_premium: 0.32f64,
            resource_curse_strength: 0.04f64,
            curse_openness_buffer: 0.35f64,
            curse_capital_buffer: 0.25f64,
            inclusive_investment_gain: 0.12f64,
            inclusive_productivity_gain: 0.65f64,
            extractive_capital_erosion: 0.045f64,
            secondary_city_bonus: 0.75f64,
            secondary_city_target: 16.0f64,
            secondary_city_spread: 0.72f64,
            metropolitan_overstretch_threshold: 22.0f64,
            metropolitan_overstretch_penalty: 0.05f64,
            endogenous_growth_rate: 0.0,
            endogenous_growth_decay: 0.72f64,
            endogenous_decline_rate: 0.0,
            active_extraction_pressure: 0.0,
            active_resource_depletion: 0.0,
            active_openness_drag: 0.0,
            active_decay_onset: 0,
            trade_cluster_count: 0,
            trade_cluster_radius: 0.18f64,
            trade_cluster_openness_bonus: 0.0,
            trade_cluster_capital_bonus: 0.0,
            trade_cluster_accessibility_bonus: 0.0,
            boomtown_count: 0,
            boomtown_resource_bonus: 0.0,
            boomtown_geography_penalty: 0.0,
            boomtown_initial_extraction_boost: 0.0,
            boomtown_early_reward_bonus: 0.0,
            boomtown_bonus_duration: 0,
            boomtown_collapse_penalty: 0.0,
            boomtown_collapse_threshold: 0,
            boomtown_decay_multiplier: 1.0f64,
            thompson_posterior_decay: 0.995f64,
            discounted_ucb_gamma: 0.97f64,
            sliding_window_ucb_window: 40,
            discounted_thompson_posterior_decay: 0.94f64,
            linucb_alpha: 1.15f64,
            linear_bandit_ridge: 1.0f64,
            linear_thompson_observation_variance: 9.0f64,
            linear_thompson_sampling_scale: 1.0f64,
            reform_sensitivity: 3.0f64,
            reform_step: 0.18f64,
            reform_duration: 5,
            reform_cost: 0.2f64,
            shock_reform_memory: 0,
            shock_reform_bonus: 0.0,
            shock_reform_step_bonus: 0.0,
            shock_openness_bonus: 0.0,
            shock_capital_rebuild: 0.0,
            shock_transition_duration: 0,
            shock_transition_adaptability_bonus: 0.0,
            shock_transition_curse_buffer: 0.0,
            shock_transition_extraction_decay: 0.0,
            shock_transition_extraction_cap: 1.0f64,
            shock_transition_openness_gain: 0.0,
            shock_transition_capital_gain: 0.0,
            shock_legacy_fade: 0.0,
            shock_legacy_adaptability_bonus: 0.0,
            shock_legacy_curse_buffer: 0.0,
            shock_legacy_extraction_decay: 0.0,
            shock_legacy_extraction_brake: 0.0,
            shock_legacy_openness_gain: 0.0,
            shock_readiness_weight: 0.0,
            shock_lock_in_bonus: 0.0,
            shock_snapback_pressure: 0.0,
            shock_probability: 0.0,
            depletion_rate: 0.18f64,
            shock_target_resource_bias: 0.0,
            geography_weights: (0.28f64, 0.18f64, 0.2f64, 0.16f64, 0.18f64),
            spine_height: 0.9f64,
            spine_curvature: 1.45f64,
            taper_offset: 0.35f64,
            taper_curvature_x: 0.45f64,
            taper_bias_x: 0.15f64,
            taper_linear_x: 0.55f64,
            headland_height: 0.28f64,
            headland_x: 0.45f64,
            mainland_bridge_height: 0.22f64,
            shock_readiness_base: 0.35f64,
            shock_legacy_readiness_base: 0.25f64,
            reform_openness_gain: 0.08f64,
            reform_adaptability_gain: 0.35f64,
            passive_investment_scale: 0.45f64,
            network_openness_influence: 0.035f64,
            growth_structural_weight: 0.9f64,
            migration_threshold: 0.75f64,
            lod: "LOW".to_string(),
            run_id: 0,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Site {
    pub id: i32,
    pub x: f64,
    pub y: f64,
    pub port_access: f64,
    pub river_access: f64,
    pub arability: f64,
    pub defensibility: f64,
    pub accessibility: f64,
    pub resource_rent: f64,
    pub suitability: f64,
    pub boomtown: bool,
    pub boomtown_reward_bonus: f64,
    pub boomtown_bonus_duration: i32,
    pub boomtown_collapse_penalty: f64,
    pub boomtown_collapse_threshold: i32,
    pub boomtown_decay_multiplier: f64,
    pub boomtown_initial_extraction_boost: f64,
    pub trade_cluster: bool,
    pub trade_cluster_openness_bonus: f64,
    pub trade_cluster_capital_bonus: f64,
}

impl Default for Site {
    fn default() -> Self {
        Self {
            id: Default::default(),
            x: Default::default(),
            y: Default::default(),
            port_access: Default::default(),
            river_access: Default::default(),
            arability: Default::default(),
            defensibility: Default::default(),
            accessibility: Default::default(),
            resource_rent: Default::default(),
            suitability: Default::default(),
            boomtown: false,
            boomtown_reward_bonus: 0.0,
            boomtown_bonus_duration: 0,
            boomtown_collapse_penalty: 0.0,
            boomtown_collapse_threshold: 0,
            boomtown_decay_multiplier: 1.0f64,
            boomtown_initial_extraction_boost: 0.0,
            trade_cluster: false,
            trade_cluster_openness_bonus: 0.0,
            trade_cluster_capital_bonus: 0.0,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct InstitutionState {
    pub extraction: f64,
    pub openness: f64,
    pub adaptability: f64,
    pub reform_timer: i32,
}

impl Default for InstitutionState {
    fn default() -> Self {
        Self {
            extraction: Default::default(),
            openness: Default::default(),
            adaptability: Default::default(),
            reform_timer: 0,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct SiteState {
    pub site: Site,
    pub institution: InstitutionState,
    pub resource_rent: f64,
    pub productive_capital: f64,
    pub initial_productive_capital: f64,
    pub population: i32,
    pub population_momentum: f64,
    pub last_reward: f64,
    pub reward_delta: f64,
    pub cumulative_reward: f64,
    pub reforms_triggered: i32,
    pub shock_hits: i32,
    pub initial_resource_rent: f64,
    pub initial_extraction: f64,
    pub initial_openness: f64,
    pub initial_adaptability: f64,
    pub first_shock_step: Option<i32>,
    pub shock_memory: i32,
    pub post_shock_timer: i32,
    pub shock_reform_stock: f64,
    pub shock_readiness: f64,
    pub post_shock_persistence: f64,
}

impl Default for SiteState {
    fn default() -> Self {
        Self {
            site: Default::default(),
            institution: Default::default(),
            resource_rent: Default::default(),
            productive_capital: 0.0,
            initial_productive_capital: 0.0,
            population: 1,
            population_momentum: 0.0,
            last_reward: 0.0,
            reward_delta: 0.0,
            cumulative_reward: 0.0,
            reforms_triggered: 0,
            shock_hits: 0,
            initial_resource_rent: 0.0,
            initial_extraction: 0.0,
            initial_openness: 0.0,
            initial_adaptability: 0.0,
            first_shock_step: None,
            shock_memory: 0,
            post_shock_timer: 0,
            shock_reform_stock: 0.0,
            shock_readiness: 0.0,
            post_shock_persistence: 0.0,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct SiteStateSnapshot {
    pub site_id: i32,
    pub x: f64,
    pub y: f64,
    pub boomtown: bool,
    pub trade_cluster: bool,
    pub extraction: f64,
    pub openness: f64,
    pub adaptability: f64,
    pub resource_rent: f64,
    pub productive_capital: f64,
    pub population: i32,
    pub shock_reform_stock: f64,
    /// Precomputed `base_geography(site, config)` for contextual / Whittle policies.
    pub geography: f64,
    pub reform_timer: i32,
    pub boomtown_reward_bonus: f64,
    pub boomtown_bonus_duration: i32,
    pub boomtown_collapse_threshold: i32,
    pub boomtown_collapse_penalty: f64,
    pub boomtown_decay_multiplier: f64,
}

impl Default for SiteStateSnapshot {
    fn default() -> Self {
        Self {
            site_id: Default::default(),
            x: Default::default(),
            y: Default::default(),
            boomtown: Default::default(),
            trade_cluster: Default::default(),
            extraction: Default::default(),
            openness: Default::default(),
            adaptability: Default::default(),
            resource_rent: Default::default(),
            productive_capital: Default::default(),
            population: Default::default(),
            shock_reform_stock: Default::default(),
            geography: Default::default(),
            reform_timer: 0,
            boomtown_reward_bonus: 0.0,
            boomtown_bonus_duration: 0,
            boomtown_collapse_threshold: 0,
            boomtown_collapse_penalty: 0.0,
            boomtown_decay_multiplier: 1.0,
        }
    }
}

