#' 01_load_data.R
#' Functions to load and preprocess Parquet and JSON artifacts from the Rust engine.

library(arrow)
library(dplyr)
library(jsonlite)
library(purrr)

#' Load Simulation Data (Parquet)
#'
#' @param dir_path Directory containing the parquet files (e.g., "results/low/")
#' @return A combined dataframe of all simulation results
load_parquet_results <- function(dir_path) {
  files <- list.files(dir_path, pattern = "\\.parquet$", full.names = TRUE)
  if (length(files) == 0) {
    warning("No parquet files found in ", dir_path)
    return(data.frame())
  }
  
  # Read Arrow Dataset
  ds <- arrow::open_dataset(dir_path, format = "parquet")
  df <- ds |> dplyr::collect()
  
  return(df)
}

#' Load Compare JSON Outputs
#'
#' @param file_path Path to the JSON file generated by the Compare command
#' @return A parsed dataframe
load_compare_json <- function(file_path) {
  if (!file.exists(file_path)) {
    stop("File not found: ", file_path)
  }
  df <- jsonlite::fromJSON(file_path, flatten = TRUE)
  return(as.data.frame(df))
}

#' Preprocess Simulation Results
#' 
#' @param df Dataframe from load_parquet_results
#' @return Preprocessed dataframe with factors and necessary transformations
preprocess_results <- function(df) {
  df <- df |>
    mutate(
      policy = as.factor(policy),
      scenario = as.factor(scenario)
    )
  
  return(df)
}

# Example Usage:
# df <- load_parquet_results("../results/low")
# df_clean <- preprocess_results(df)
